// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YouTubeChannelDownloader.Data;

namespace YouTubeChannelDownloader.Migrations
{
    [DbContext(typeof(DownloadedVideosContext))]
    partial class DownloadedVideosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("YouTubeChannelDownloader.Models.DownloadedVideo", b =>
                {
                    b.Property<string>("DownloadedVideoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DownloadedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("DownloadedVideoId");

                    b.ToTable("DownloadedVideos");
                });
#pragma warning restore 612, 618
        }
    }
}
